### ISSUE TITLE
wrong instructions on installation guide for wazigate

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziGate#148] opened 2021-03-08 01:51 UTC
Following the instructions on https://github.com/Waziup/WaziGate/blob/master/README.md yields to the installation of an OLD version 1.0 (10th Dez 2019) of the wazigate ...which in turn yields to error messages at the end of the installation ....

### pi@raspberrypi:~ $ curl -fsSL https://raw.githubusercontent.com/Waziup/waziup-gateway/master/setup/get_waziup.sh | bash
Downloading Wazigate...
WaziGate-1.0/
WaziGate-1.0/.env
WaziGate-1.0/.gitignore
WaziGate-1.0/.gitmodules
WaziGate-1.0/ChangeLog
WaziGate-1.0/README.md
WaziGate-1.0/docker-compose-build.yml
WaziGate-1.0/docker-compose-dev.yml
WaziGate-1.0/docker-compose-i386.yml
WaziGate-1.0/docker-compose.yml
WaziGate-1.0/setup/
WaziGate-1.0/setup/.gitignore
WaziGate-1.0/setup/clouds.json
WaziGate-1.0/setup/conf.default.json
WaziGate-1.0/setup/docker-compose
WaziGate-1.0/setup/get_waziup.sh
WaziGate-1.0/setup/get_waziup_dev.sh
WaziGate-1.0/setup/get_waziup_test.sh
WaziGate-1.0/setup/hostapd.conf
WaziGate-1.0/setup/install.sh
WaziGate-1.0/setup/kweb/
WaziGate-1.0/setup/kweb/kweb-1.7.9.8.tar.gz
WaziGate-1.0/setup/kweb/kweb_upgrade_buster_20190823.tar.gz
WaziGate-1.0/setup/sd-card-image.sh
WaziGate-1.0/setup/uninstall.sh
WaziGate-1.0/setup/waziup-logo.png
WaziGate-1.0/start.sh
WaziGate-1.0/stop.sh
WaziGate-1.0/wazigate-edge/
WaziGate-1.0/wazigate-host/
WaziGate-1.0/wazigate-host/buttons/
WaziGate-1.0/wazigate-host/buttons/buttons.py
WaziGate-1.0/wazigate-host/buttons/buttons.sh
WaziGate-1.0/wazigate-host/fan/
WaziGate-1.0/wazigate-host/fan/fan.py
WaziGate-1.0/wazigate-host/fan/fan.sh
WaziGate-1.0/wazigate-host/host.py
WaziGate-1.0/wazigate-host/host.sh
WaziGate-1.0/wazigate-host/init-hdmi-ui.html
WaziGate-1.0/wazigate-host/kiosk.sh
WaziGate-1.0/wazigate-host/main.go
WaziGate-1.0/wazigate-host/oled/
WaziGate-1.0/wazigate-host/oled/fonts/
WaziGate-1.0/wazigate-host/oled/fonts/C&C Red Alert [INET].ttf
WaziGate-1.0/wazigate-host/oled/fonts/ChiKareGo.ttf
WaziGate-1.0/wazigate-host/oled/fonts/FreePixel.ttf
WaziGate-1.0/wazigate-host/oled/fonts/ProggyTiny.ttf
WaziGate-1.0/wazigate-host/oled/fonts/README [INET].txt
WaziGate-1.0/wazigate-host/oled/fonts/Volter__28Goldfish_29.ttf
WaziGate-1.0/wazigate-host/oled/fonts/code2000.ttf
WaziGate-1.0/wazigate-host/oled/fonts/creep.bdf
WaziGate-1.0/wazigate-host/oled/fonts/fontawesome-webfont.ttf
WaziGate-1.0/wazigate-host/oled/fonts/miscfs_.ttf
WaziGate-1.0/wazigate-host/oled/fonts/pixelmix.ttf
WaziGate-1.0/wazigate-host/oled/fonts/tiny.ttf
WaziGate-1.0/wazigate-host/oled/msg.txt
WaziGate-1.0/wazigate-host/oled/oled.py
WaziGate-1.0/wazigate-host/oled/oled.sh
WaziGate-1.0/wazigate-host/start.sh
WaziGate-1.0/wazigate-host/start_hotspot.sh
WaziGate-1.0/wazigate-host/start_wifi.sh
WaziGate-1.0/wazigate-host/wazigate-host
WaziGate-1.0/wazigate-mongo/
WaziGate-1.0/wazigate-mongo/Dockerfile
WaziGate-1.0/wazigate-system/
WaziGate-1.0/wazigate-ui/
**mv: cannot stat 'waziup-gateway*': No such file or directory
bash: line 12: cd: waziup-gateway: No such file or directory
chmod: cannot access 'setup/install.sh': No such file or directory
chmod: cannot access 'setup/uninstall.sh': No such file or directory
sed: can't read .env: No such file or directory
bash: ./setup/install.sh: No such file or directory
sed: can't read start.sh: No such file or directory
Downloading the docker images...
sudo: docker-compose: command not found**
Done
Rebooting in 01 seconds...

**Comment by SvenZeisberg** [comment] 2021-03-08 09:48
It seems, that the script "_https://raw.githubusercontent.com/Waziup/waziup-gateway/master/setup/get_waziup.sh_" it is actually installing the gateway software into the directory "/home/pi/WaziGate-1.0" while then there is a move command in the same script trying "mv waziup-gateway* waziup-gateway", which obviously fails. ... Maybe the command should be written as "mv WaziGate* waziup-gateway"? Would that simple change already solve the issue, that the installation fails at the moment?

**Comment by SvenZeisberg** [comment] 2021-03-08 12:19
reopen

**Comment by SvenZeisberg** [comment] 2021-03-08 12:22
> It seems, that the script "_https://raw.githubusercontent.com/Waziup/waziup-gateway/master/setup/get_waziup.sh_" it is actually installing the gateway software into the directory "/home/pi/WaziGate-1.0" while then there is a move command in the same script trying "mv waziup-gateway* waziup-gateway", which obviously fails. ... Maybe the command should be written as "mv WaziGate* waziup-gateway"? Would that simple change already solve the issue, that the installation fails at the moment?

...in any case that change would not solve the issue, that an OLD version from 2019 is taken by the script. So what needs to be changed?

**Comment by SvenZeisberg** [comment] 2021-03-08 12:25
when I was overcoming the wrong directory name manually correcting and then going step by step the commands written in the https://raw.githubusercontent.com/Waziup/waziup-gateway/master/setup/get_waziup.sh script, then I did run in some more issues ...the last one is related to mongo container pull:

pi@raspberrypi:~ /waziup-gateway $ **sudo docker-compose pull**
sudo: unable to resolve host raspberrypi: Name or service not known
Pulling wazigate-mongo (waziup/wazigate-mongo:latest)...
ERROR: Get https://registry-1.docker.io/v2/ : dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:54631->127.0.0.1:53: read: connection refused
pi@raspberrypi:~ /waziup-gateway $ **sudo docker-compose pull**
sudo: unable to resolve host raspberrypi: Name or service not known
Pulling wazigate-mongo (waziup/wazigate-mongo:latest)...
ERROR: manifest for waziup/wazigate-mongo:latest not found: manifest unknown: manifest unknown
pi@raspberrypi:~/waziup-gateway $ **sudo docker-compose pull**
sudo: unable to resolve host raspberrypi: Name or service not known
Pulling wazigate-mongo (waziup/wazigate-mongo:latest)...
ERROR: manifest for waziup/wazigate-mongo:latest not found: manifest unknown: manifest unknown

**Comment by mojtaba-esk** [comment] 2021-03-09 10:26
Fixed, another script should have been used instead:

`curl -fsSL https://raw.githubusercontent.com/Waziup/waziup-gateway/master/setup/get_waziup_test.sh | bash`

The older one was designed to download the latest release and work with. Since we use ISO image, it is not used any more. Instead if someone wants to install it from its source (at their own risk), can use the above script. the main instruction is also updated.

**Comment by SvenZeisberg** [comment] 2021-03-11 13:58
The new script "curl -fsSL https://raw.githubusercontent.com/Waziup/waziup-gateway/master/setup/get_waziup_test.sh | bash" applied on a totally fresh installed "Rasperry Pi OS lite" ended with the error messages shown in the screenshot and then rebootet the Pi in AP mode. Also there was no access via Ethernet possible anymore. Because the docker installation failed one could not access any GUI via AP WiFi, only ssh via AP WiFi was possible. 
![image](https://user-images.githubusercontent.com/62630067/110798265-43cc1000-827a-11eb-95d0-db58d7e64ad5.png)

How to get out of this situation then???
Now there would be the right point in time to have an option on the ssh cmd line to configure the Pi 1) to get back the Ethernet access feature in order to get it connected to the Internet again and 2) to try an other/alternative install/repair script to get the waziup gateway software and start it ...

@Mojtaba: Please try your script on a totally fresh installed Raspian OS lite (on a Pi 3b) and please confirm, that you see the same behaviour, which I see.

**Comment by cdupont** [comment] 2021-11-05 14:54
Closing as obsolete. New installation method is only with ISO.

**Closed as completed by cdupont** 2021-11-05 14:54 UTC
Labels: bug
