### ISSUE TITLE
V2.0 (Beta) LoRaWAN Sensor added on the wrong device

### ISSUE THREAD

**Issue by MattiaMoretto97** [Waziup/WaziGate#77] opened 2020-06-24 10:20 UTC
The temperature sensor was added on wrong device: it should be on "MyDeviceTest" (LoRaWAN device). 

![image](https://user-images.githubusercontent.com/64007834/85537856-a1e59400-b614-11ea-9696-42ea5c46429c.png)

**Comment by cdupont** [comment] 2020-10-30 11:15
I had this problem today.
![image](https://user-images.githubusercontent.com/484033/97698860-851d0980-1aa9-11eb-8052-88bcd8a3106c.png)

The device "test" is configured with LoRaWAN details. But the data appears on the Gateway.

**Comment by j-forster** [comment] 2020-11-03 10:08
This issue adds some insecurity to the platform, but we decides to skip the frame-counter validation to make the development with Wazidev and Wazigate easier.
The issue is resolved by https://github.com/Waziup/wazigate-lora/commit/63d810c9cd3781ce7ae02a6dc9868b86a72d81de.

**Comment by j-forster** [comment] 2020-11-05 11:00
This issue has been fixed by https://github.com/Waziup/wazigate-lora/commit/95def9f85e6028768ea84a770308e686f3160d34.

**Closed as completed by j-forster** 2020-11-05 11:00 UTC
Labels: bug
