### ISSUE TITLE
Size of images is big

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#15] opened 2019-08-09 08:12 UTC
```
waziup/wazigate-system  V1.0-beta1          ae5756e517e4        5 weeks ago         908MB
waziup/wazigate-ui      V1.0-beta1          7debe83d1eda        4 weeks ago         782MB
```

**Comment by j-forster** [comment] 2019-08-29 11:32
The image sizes of [wazigate-system](https://github.com/Waziup/wazigate-system) and [wazigate-ui](https://github.com/Waziup/wazigate-ui) are huge compared to the [wazigate-edge](https://github.com/Waziup/wazigate-edge) (14.6MB). Don't forget the MongoDB (273MB). 

The sizes of wazigate-system and wazigate-ui result from PHP and Python used in those images and I am not sure if a multi-stage dockerfile can improve this. For wazigate-ui it definitely can't.

@mojtaba-esk  might test the multi-stage dockerfile if that is possible with wazigate-system, so I will close this issue (it's not a bug) and open a new one at the system repo.

There are a few more things we might do in the future to reduce the image sizes:

- combine wazigate-ui and -system in one image so that they both use the same PHP image 
- use a more IoT friendly language for these tasks, like Python or Go

**Closed as completed by j-forster** 2019-08-29 11:32 UTC
Labels: enhancement

**Comment by cdupont** [comment] 2019-10-11 16:12
Done, I changed the Dockerfiles to use Alpine Linux. Images are down to ~170Mo.
https://github.com/Waziup/wazigate-system/blob/master/Dockerfile
https://github.com/Waziup/wazigate-ui/blob/master/Dockerfile
